### ISSUE TITLE
Importing interface from vue component

### ISSUE THREAD

**Issue by germanp** [vuejs/vue-jest#189]
Hey, 

I'm using ts-jest with vue-jest but I can't import interfaces from the .vue component files. I'm getting this error:

```
Module '"*.vue"' has no exported member 'Option'.
```

Does vue-jest support exporting interfaces? or maybe it is not related with vue-jest. Anyway, I appreciate some guidance on that. Thanks

**Comment by gumchum** [comment]
Also running into this issue.

**Comment by JordanMajd** [comment]
I think this is the same issue, if not I can split into my own.  While using jest + typescript I can't import non-default exports from `.vue` files. Although, I have no issue doing this with other `.ts` files while running my standard build. The following example would produce: `TS2614: Module '"*.vue"' has no exported member 'IMyComponent'. Did you mean to use 'import IMyComponent from "*.vue"' instead?`

MyComponent.vue
```ts
<template>
...
</template>
<script lang="ts">
export interface IMyComponent extends Vue {
  ...
};
export default Vue.extend({
 ...
});
</script>
```


MyComponent.spec.ts (compiles fine normal build, blows up when running jest)
```ts
import MyComponent, { IMyComponent } from "../mycomponent.vue";
```

SomeOther.ts (compiles fine normal build)
```ts
import MyComponent, { IMyComponent } from "../mycomponent.vue";
```

**Comment by freezer278** [comment]
same issue

**Comment by jackdomleo7** [comment]
Any further progression on this? 🤔

Currently, I have to write this just as a mental note of what the interface is:

```ts
import MyComponent/*, { IMyComponent }*/ from "../mycomponent.vue"
```

because as @JordanMajd mentions, writing the below just doesn't work:

```ts
import MyComponent, { IMyComponent } from "../mycomponent.vue"
```

**Comment by jackdomleo7** [comment]
Hi, please find a repository [here](https://github.com/jackdomleo7/vue-jest-interface-repro) with the repro steps listed in the project's README. 🤞

**Comment by james75** [comment]
I'm also experiencing this, any solution?

**Comment by jackdomleo7** [comment]
@james75 Nope. There are currently 2 indirect solutions (but ideally we want someone maintaining this repo to respond to this issue):

1. Move your interfaces into a separate file
2. Test without the types

**Comment by JordanMajd** [comment]
Giving this a 2021 bump, I'm happy to help with the solution.

**Comment by tylerrrkd** [comment]
> Giving this a 2021 bump, I'm happy to help with the solution.

Hi friend, do you have any solution? Exporting interface inside component is much convenient for component file.

**Comment by MatthD** [comment]
It's still the case, we cannot import types from component in TS files.. but it work in another .vue file !

**Comment by AlaaEl-DinAhmed** [comment]
I guess it's solved with TypeScript 3.8 as we can add type before the type name import.

`import MyComponent, { type IMyComponent } from "../mycomponent.vue";`

More details [type-only imports — A new TypeScript feature that benefits Babel users
](https://levelup.gitconnected.com/improving-babel-support-for-typescript-with-type-only-imports-28cb209d9460)

**Comment by jackdomleo7** [comment]
> I guess it's solved with TypeScript 3.8 as we can add type before the type name import.
> 
> `import MyComponent, { type IMyComponent } from "../mycomponent.vue";`
> 
> More details [type-only imports — A new TypeScript feature that benefits Babel users ](https://levelup.gitconnected.com/improving-babel-support-for-typescript-with-type-only-imports-28cb209d9460)

@AlaaEl-DinAhmed, I tried your suggest in my [repro repo](https://github.com/jackdomleo7/vue-jest-interface-repro) and still getting the same result.

![image](https://user-images.githubusercontent.com/43371432/212197285-58e7e58e-f439-457c-bd9e-f87ddd39cd73.png)

**Comment by jackdomleo7** [comment]
> Hi, please find a repository [here](https://github.com/jackdomleo7/vue-jest-interface-repro) with the repro steps listed in the project's README. 🤞 Can the `needs repro` tag be removed?

FYI I have deleted this reproduction repository due to it being available for 2.5 years and no activity on this issue. I have also switched to Vitest for almost all of my projects so this issue is no longer of interest to me.
