### ISSUE TITLE
Code coverage seems to be collected incorrectly

### ISSUE THREAD

**Issue by sam-pastoriza** [vuejs/vue-jest#329]
I am looking to upgrade several projects to Vue 3 and I am running into an interesting issue when collecting code coverage. For some reason, when switching to Vue 3, the **code coverage statistics are incorrect, but the tests are running correctly**. Below is a repository that minimally reproduces the issue I am running into. Also attached are a couple of screenshots that show the difference in coverage between Vue 2 and Vue 3.

https://github.com/sam-pastoriza/vue-3-coverage

With Vue 2, you get the following coverage in the repo.
![image](https://user-images.githubusercontent.com/72568995/113421403-0d754280-9399-11eb-8c4a-e9162806fb9c.png)
With Vue 3, you get the following coverage, without changing the tests.
![image](https://user-images.githubusercontent.com/72568995/113421443-1fef7c00-9399-11eb-83fd-97a284862039.png)

A readme file in that repository details how I switch between Vue 2 and Vue 3.

A couple of notes on the structure of the project I am working with.
* We use `vue-class-component` as a library. I don't think this is causing the issue, but I could be wrong.
* We are required to split up the components into separate .ts and .vue files.

Many thanks for the help. Hopefully this is the right place to post this issue.

**Comment by jolting** [comment]
Try setting the fileName option here. https://github.com/vuejs/vue-jest/blob/acab46325633e641f245bcce4d12ed5259d1ea96/lib/process.js#L107

Should be filename or template.src if set.

**Comment by sam-pastoriza** [comment]
@lmiller1990 Thanks for the help! Much appreciated.

**Comment by sam-pastoriza** [comment]
@jolting Is that something I can do on my end on the tsconfig.json?

**Comment by saksham-malhotra** [comment]
> @jolting Is that something I can do on my end in the tsconfig.json?

I guess not. He is referring to the file vue-jest/lib/process.js

**Comment by jolting** [comment]
@saksham-malhotra yeah, t's a code change. I ran into similar things when the file name was wrong on the source maps. module.tsx is the default for transpileModule if you don't give it a filename. 
See here
https://github.com/microsoft/TypeScript/blob/2428ade1a91248e847f3e1561e31a9426650efee/src/services/transpile.ts#L50

**Comment by jolting** [comment]
@saksham-malhotra try #330

**Comment by sam-pastoriza** [comment]
I can try it when I get a chance today

**Comment by lmiller1990** [comment]
It is actually REALLY easy to test if this work locally for this package. There is no babel, not typescript, no compilation, no bullshit, all you need to do is modify the code in `node_modules/vue-jest/lib` and run jest with `--no-cache` and you'll see if your fix worked. This is how I normally work on vue-jest for problems that are difficult to reproduce.

If you find a fix, let's work together and get it merged. Getting everything to work is pretty tricky due to the amount of transformations that are applied, eg often you go from `vue` -> `ts` -> `js` etc... but it would be great to get code coverage working accurately.

**Comment by jolting** [comment]
@lmiller1990 #331 should fix this.

**Comment by lmiller1990** [comment]
🍻  Merged. thanks!

I usually do release at the end of the week, please wait a few days everyone.

**Comment by sam-pastoriza** [comment]
Following up on this, it looks like it does work better. It still doesn't exactly match the output of Vue 2, but this works for me in my case. 
![image](https://user-images.githubusercontent.com/72568995/113709089-17a48300-96b0-11eb-821b-41be2abc172a.png)

**Comment by jolting** [comment]
The vue2 output was wrong.

**Comment by sam-pastoriza** [comment]
@lmiller1990 Any chance of this update being released soon?

**Comment by lmiller1990** [comment]
I will do a release by the end of this week, since we had a bunch of stuff merged up. I didn't realize it had been so long since we did a release on the next branch.

**Comment by lmiller1990** [comment]
It's out:

https://github.com/vuejs/vue-jest/releases/tag/v5.0.0-alpha.9
